### ISSUE TITLE
Avesis sitesine göre script düzenlenmeli

### ISSUE THREAD

**Issue by f9n** [GnuYtuce/ytuce-file-holder#2]
http://avesis.yildiz.edu.tr

**Comment by maliayas** [comment]
Merhaba Fatih,

Reponu tesadüfen gördüm. Güzel bir çalışma olmuş.

https://ytuce.maliayas.com epey bir süredir dosyaların da arşivini tutuyor. Avesis gibi yenilikler bu tür botları sürekli patlattığı için bu işlerin ne kadar zor olduğunun farkındayım. O nedenle YTÜ CE ile ilgili işlerinde kaynak olarak orijinal site yerine https://ytuce.maliayas.com 'u kullanabilirsin; böylece aynı zahmeti tekrar çekmiş olmazsın.

**Comment by f9n** [comment]
Merhaba,
Teşekkürler, Sizin sayenizde bölümün haberlerini alıyoruz. Elinize sağlık.

**Comment by maliayas** [comment]
Rica ederim. Güle güle kullanın. Forumu da kullanmanızı beklerdim ama sanırım yeni nesiller artık forum kullanmıyor :) 2005-2010 larda forumun çok hayati bir fonksiyonu vardı bizde.

**Comment by buraksarica** [comment]
Merhaba,

avesis’ten hangi veriyi çekmek istiyorsunuz? Konuyu istişare edebiliriz.

**Comment by kaansonmezoz** [comment]
Merhaba,

Avesis'in authentication gerekmeden kullanabileceğimiz  Rest Api ya da data çekebileceğimiz endpointleri var mı ? 

Biz şuanda 3 tane data çekmeyi düşünüyoruz. Bunlar:

- Bir üniversitedeki fakültelerin listesini,
- Bir fakülteye ait bölümlerin listesini,
- Bir bölümdeki hocaların listesini

Veya hocaların fakülte ve bölüm bilgisiyle birlikte tüm listesinin dönüldüğü bir endpointiniz var mı ?
